import { ArrowRight, Compass, Flag, Lightbulb, Map, Sparkles } from "lucide-react";
import { useState } from "react";
import { api } from "../lib/api.js";
import { useToast } from "../context/ToastContext.jsx";

export default function Career() {
  const { showToast } = useToast();
  const [form, setForm] = useState({ currentRole: "Computer science student", interests: "frontend engineering, product design, and meaningful consumer products" });
  const [guidance, setGuidance] = useState(null);
  const build = async (e) => { e.preventDefault(); try { setGuidance(await api("/career-guidance", { method: "POST", body: form })); showToast("Your roadmap is ready"); } catch (err) { showToast(err.message, "error"); } };
  return <div className="page-enter"><div className="page-heading"><span className="eyebrow">Career compass</span><h1>Turn curiosity into direction.</h1><p>Build a grounded six-month roadmap around your strengths and the work you want to explore.</p></div>{!guidance ? <div className="tool-grid"><form className="panel tool-form" onSubmit={build}><span className="feature-icon"><Compass size={24} /></span><h2>Tell us where you are</h2><label>Current role or stage<input value={form.currentRole} onChange={(e) => setForm({ ...form, currentRole: e.target.value })} /></label><label>What kind of work interests you?<textarea rows="7" value={form.interests} onChange={(e) => setForm({ ...form, interests: e.target.value })} /></label><button className="button primary full">Build my roadmap <Sparkles size={17} /></button></form><aside className="panel tool-aside"><span className="feature-icon"><Map size={24} /></span><h2>You’ll receive</h2><ul><li><Lightbulb size={17} />Possible next roles</li><li><Flag size={17} />Skill gaps worth closing</li><li><Compass size={17} />A six-month action plan</li></ul></aside></div> : <div className="career-report"><section className="panel career-summary"><span className="section-kicker">Your direction</span><h2>{guidance.title}</h2><p>{guidance.summary}</p></section><div className="report-grid"><section className="panel"><h2>Roles to explore</h2>{guidance.nextRoles.map((role, i) => <div className="role-path" key={role}><span>0{i + 1}</span><strong>{role}</strong><ArrowRight size={17} /></div>)}</section><section className="panel"><h2>Skills to strengthen</h2><div className="skill-gap-list">{guidance.skillGaps.map((skill, i) => <div key={skill}><span style={{ width: `${72 - i * 11}%` }} /><strong>{skill}</strong></div>)}</div></section></div><section className="panel roadmap"><h2>Your six-month roadmap</h2>{guidance.roadmap.map((step, i) => <div className="roadmap-step" key={step.month}><span>{i + 1}</span><div><strong>{step.month}</strong><p>{step.focus}</p></div></div>)}</section></div>}</div>;
}
