import { ArrowRight, BriefcaseBusiness, Check, Plus, Sparkles } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext.jsx";
import { api } from "../lib/api.js";
import { useToast } from "../context/ToastContext.jsx";

export default function PostJob() {
  const { user } = useAuth(); const navigate = useNavigate(); const { showToast } = useToast();
  const [form, setForm] = useState({ title: "", company: user.company || "", location: "", type: "Internship", workplace: "Hybrid", salary: "", description: "", skills: "", requirements: "", responsibilities: "", benefits: "Flexible schedule, Mentorship, Certificate", deadline: "" });
  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  const submit = async (e) => { e.preventDefault(); try { const arrays = ["skills","requirements","responsibilities","benefits"]; const payload = { ...form, ...Object.fromEntries(arrays.map((key) => [key, form[key].split(",").map((v) => v.trim()).filter(Boolean)])) }; await api("/jobs", { method: "POST", body: payload }); showToast("Your opportunity is live"); navigate(user.role === "admin" ? "/admin/jobs" : "/employer/jobs"); } catch (err) { showToast(err.message, "error"); } };
  return <div className="post-job-page page-enter"><div className="page-heading"><span className="eyebrow">Create an opportunity</span><h1>Tell the real story of the role.</h1><p>Clear expectations help the right people recognize themselves in your opening.</p></div><form className="panel post-job-form" onSubmit={submit}><section><div className="form-section-title"><span>1</span><div><h2>The essentials</h2><p>Help candidates understand the opportunity at a glance.</p></div></div><div className="form-grid"><label className="full">Role title<input name="title" value={form.title} onChange={update} placeholder="e.g. Product Design Intern" required /></label><label>Company<input name="company" value={form.company} onChange={update} required /></label><label>Location<input name="location" value={form.location} onChange={update} placeholder="e.g. Bengaluru or Remote" required /></label><label>Opportunity type<select name="type" value={form.type} onChange={update}><option>Internship</option><option>Full-time</option><option>Part-time</option><option>Contract</option></select></label><label>Work style<select name="workplace" value={form.workplace} onChange={update}><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label>Compensation<input name="salary" value={form.salary} onChange={update} placeholder="₹25k – ₹35k / month" /></label><label>Application deadline<input type="date" name="deadline" value={form.deadline} onChange={update} /></label></div></section><section><div className="form-section-title"><span>2</span><div><h2>The work and the person</h2><p>Use plain language and focus on what truly matters.</p></div></div><label>Opportunity summary<textarea rows="5" name="description" value={form.description} onChange={update} required /></label><label>Skills <small>Comma separated</small><input name="skills" value={form.skills} onChange={update} placeholder="Figma, UX research, Prototyping" /></label><label>Responsibilities <small>Comma separated</small><textarea rows="4" name="responsibilities" value={form.responsibilities} onChange={update} /></label><label>Requirements <small>Comma separated</small><textarea rows="4" name="requirements" value={form.requirements} onChange={update} /></label><label>Benefits <small>Comma separated</small><input name="benefits" value={form.benefits} onChange={update} /></label></section><div className="publish-bar"><div><Sparkles size={18} /><span><strong>Ready when you are.</strong><small>You can edit or close this role later.</small></span></div><button className="button primary">Publish opportunity <ArrowRight size={17} /></button></div></form></div>;
}
